### ISSUE TITLE
linked tables - Chokes on Relations export: Bad file name or number

### ISSUE THREAD

**Issue by p0lar-bear** [timabell/msaccess-vcs-integration#10] opened 2015-04-29 17:21 UTC
I've been put in charge of managing an Access database that's been around for a while (so it's in MDB format), and when I installed this to try out possible version control solutions, it gets caught up on the relationship export and throws a error 52 "Bad file name or number".

On closer inspection I find that the reason this happens is because my relationships are named as such: [&lt;full path to MDB file&gt;].[&lt;guid&gt;]

EDIT: Actually, only one relationship is a GUID. The rest of them are like [&lt;full path to MDB file&gt;].[&lt;TableOneTableTwo&gt;]

Can anyone suggest a workaround for this?

**Comment by jwbrookes** [comment] 2015-04-30 07:22
>On closer inspection I find that the reason this happens is because my __relationships__ are named as such: [\<full path to MDB file>].[\<guid>]

Don't you mean references?

**Comment by jwbrookes** [comment] 2015-04-30 07:41
That style of name is invalid in access (it won't allow dots). So I'm not sure how you have any object named in that format.

**Comment by p0lar-bear** [comment] 2015-04-30 22:06
I'm not quite sure either, especially considering that one can't name Relationships in an access database... and yes, I'm certain that these are relationships and not references, based on where the error occurred in the code.

**Comment by jwbrookes** [comment] 2015-05-05 09:18
I've created a fix in a new branch called `RelationNameMDB`. Could try this out and report back?

I'm not sure if this will work, as I can't reproduce your relation names. I expect it will export the relations but will fail to import them.

What version of Access are you using?

**Comment by p0lar-bear** [comment] 2015-05-05 13:57
I'm using Access 2013. Next chance I get I'll try your branch.

**Comment by stessler** [comment] 2015-05-16 19:46
I find this problem occurs because Access recognizes relationships in linked tables (within the backend) and tries to create a filename for the relationship to put in /source/relations - problem is that the name contains square brackets for linked table relations. 

As noted above, Access makes the default relationship name something like [<full path to MDB file>].[<relationname>] - the brackets and dots in the path are literal, and can't be used to construct a filename in /source.

My solution is to exclude backend relationships, because I don't need them when documenting a frontend.
If Not Left(aRelation.name,1) = "[" then ... send it to ExportRelation sub.

I'm just learning Git. Maybe it'll start being fun soon.

**Comment by CrispinF** [comment] 2015-05-16 20:24
I found this same issue today, though I think it is actually not the brackets and dots causing issues, but the fact that the external relation has a path that really cannot be used in a filename (e.g. "[H:\Myfolder\mydb.mdb].mytable"). My solution was to keep these relations, but fix the filename as follows
VCS_Relation.ExportRelation aRelation, obj_path & Replace(Replace(aRelation.Name, "\", "_backslash_"), ":", "_colon_") & ".txt"
And this does work for the export.
But I agree that perhaps these backend relations are just not relevant, so I might switch to just excluding them.

**Comment by stessler** [comment] 2015-05-16 23:06
Yes, exactly, I'll borrow your approach. I've added an optional Public Const SKIP_LINKED_TABLES = True to my code, and use it block linked tabledefs and data in the output. Now they're optional. Most of the time I'm updating forms and modules and don't need to refresh table/link info for versioning. 
Still very new to figuring out how I should set up folders (multiple projects) for using a Git workflow.

**Comment by p0lar-bear** [comment] 2015-06-05 14:49
First off, I never got a chance to try that branch, @jwbrookes.

Second, what @stessler makes a lot of sense and I never would have thought to mention that my database was a frontend with linked tables. It would appear that just about all of these relationships are  from a backend database.

The question I have now is, can we safely ignore backend relationships? I.E. if I run this importer on an empty database and it loads in all of the table links, will it automatically populate itself with the relationships from the backend? I would think this to be the case, but this is Microsoft Access - making assumptions based on solid logic is very dangerous.

**Comment by p0lar-bear** [comment] 2015-06-05 16:29
The answer is yes - the linked tables will populate the front-end with relationships, at least when you import the objects into a blank DB.

__HOWEVER__

I noticed that in my front-end, the relationships had been edited at some point manually and only have a handful of the relationships defined in the backend.

I don't know how common this practice might be, or if this will break anything in my front-end, but just excluding the defined relationships as a blanket solution potentially won't work for me. Moreover, it would seem that the import functionality should be extended to delete all existing relationships before importing existing ones.

**Comment by Ronaldvr** [comment] 2015-07-13 11:14
Perhaps I am captain obvious, but why is the solution not to just create 1 single file for all relations, and name it after the Database? The you lose all the issues ith characters.

**Comment by Ronaldvr** [comment] 2015-07-31 13:08
I created an XML export and import for this that works around the filename issue since this is created in 1 single file (Relations.xml) What I did find however was that there is another issue, and that is that the relation Name may not be longer than 64 characters, but that the export *does* create longer names than that! And this in turn creates a name clash when the import uses these names. So I replace these names with generated names. However this obviously again makes the filename creation point moot... Code below

```vba
Public Sub ExportRelation(rel As dao.Relation, outfile As Variant)
    Dim f As dao.Field
    Dim strNm As String
    
    outfile.WriteLine "<Relation>"
    If InStr(rel.name, ":\") > 0 Then
        'names with linked table names get unwieldy long and left(64) thus not very descriptive, and may even cause a same name clash
        strNm = Replace(rel.Table & "_" & rel.Fields(0).name, " ", "_") & "_to_" & Replace(rel.ForeignTable & "_" & rel.Fields(0).ForeignName, " ", "_")
    Else
        strNm = rel.name
    End If

    outfile.WriteLine "<RelationName>" & Right(strNm, 64) & "</RelationName>"
    outfile.WriteLine "<RelationAttributes>" & rel.Attributes & "</RelationAttributes>" 'RelationAttributeEnum
    outfile.WriteLine "<RelationTable>" & rel.Table & "</RelationTable>"
    outfile.WriteLine "<RelationforeignTable>" & rel.ForeignTable & "</RelationforeignTable>"
    outfile.WriteLine "<Fields>"
    For Each f In rel.Fields
        outfile.WriteLine "<FieldName>" & f.name & "</FieldName>"
        outfile.WriteLine "<FieldForeignName>" & f.ForeignName & "</FieldForeignName>"
    Next
    outfile.WriteLine "</Fields>"
    outfile.WriteLine "</Relation>"

End Sub
Public Function ImportRelation(filePath As String) As Long

Dim xmlDoc As Object
Set xmlDoc = CreateObject("MSXML2.DOMDocument")
Dim xmlNode As Object 'MSXML2.IXMLDOMNode
Dim xmlFldNode As Object 'MSXML2.IXMLDOMNode
Dim xmlElements As Object 'MSXML2.IXMLDOMNode
Dim xmlElements1 As Object 'MSXML2.IXMLDOMNode
Dim xmlElements2 As Object 'MSXML2.IXMLDOMNode
Dim I As Integer
Dim n As Long
Dim strNm As String
Dim rel As dao.Relation
Dim FLd As dao.Field

xmlDoc.async = False
xmlDoc.Load filePath
n = 0
For Each xmlNode In xmlDoc.FirstChild.ChildNodes
    Set rel = New dao.Relation
    Set xmlElements = xmlNode.getElementsByTagName("RelationTable")
    rel.Table = xmlElements.item(0).Text
    Set xmlElements = xmlNode.getElementsByTagName("RelationforeignTable")
    rel.ForeignTable = xmlElements.item(0).Text
    Set xmlElements = xmlNode.getElementsByTagName("RelationAttributes")
    rel.Attributes = CLng(xmlElements.item(0).Text)
    Set xmlFldNode = xmlNode.SelectSingleNode("Fields")
    Set xmlElements1 = xmlNode.getElementsByTagName("FieldName")
    Set xmlElements2 = xmlNode.getElementsByTagName("FieldForeignName")
    For I = 0 To xmlElements1.Length - 1
        Set FLd = New dao.Field
        FLd.name = xmlElements1.item(I).Text
        FLd.ForeignName = xmlElements2.item(I).Text
        rel.Fields.Append FLd
    Next
    strNm = Replace(rel.Table & "_" & rel.Fields(0).name, " ", "_") & "_to_" & Replace(rel.ForeignTable & "_" & rel.Fields(0).ForeignName, " ", "_")
    Set xmlElements = xmlNode.getElementsByTagName("RelationName")
    If InStr(xmlElements.item(0).Text, ":\") > 0 Then
        'names with linked table names get unwieldy long and left(64) thus not very descriptive, and may even cause a same name clash
        rel.name = Left(strNm, 64)
    Else
        rel.name = Right(xmlElements.item(0).Text, 64)
    End If
    CurrentDb.Relations.Append rel
    n = n + 1
Next

ImportRelation = n

End Function

```

**Comment by mgrojo** [comment] 2015-08-16 11:40
I had this same problem. I have worked around it by cleaning the filename of incorrect characters:

In VCS_File I have added:
```VB
' Clean a file name of invalid characters replacing them with "_"
Function CleanFileName(strFileName As String) As String
  Dim Invalids, e, strTemp As String
  Invalids = Array("?", "*", ":", "|", "<", ">", "[", "]", "\", "/")
  strTemp = strFileName
  For Each e In Invalids
    strTemp = Replace(strTemp, e, "_")
  Next
  CleanFileName = strTemp
End Function
```
and I have used this function before the ExportRelation call in VCS_ImportExport (line 190):
```VB
            VCS_Relation.ExportRelation aRelation, obj_path & CleanFileName(aRelation.name) & ".txt"
```
This is not apparently affecting the import, unless when the problem with the 64 characters is not present. Nevertheless I've not been unable to import all my files, but due to other problems that I am currently investigating.

**Comment by mgrojo** [comment] 2015-08-16 16:45
I had this same problem. My conclusion is that there is no sense in exporting these relations, since they are "linked" when their tables are linked.

The best approach would be to export the backend too (where the real relations can be exported without problems). Here we have the table definitions which are not exported in the fronted, so it is also useful because of that.

Then we can export the frontend in a different path, excluding these linked relations as @stessler suggests.

For the import, the backend must be recreated first and then the frontend. When the links are imported, the relations appear again in the database.

The difficult part is that, when the database is structured in this way, the backend cannot be usually  recreated because it is in production and has new data that cannot be lost. If you have changed the backend table definitions or the relations, you have to perform an upgrade of the backend. So the conclusion is that the importing for the backend is not indeed very useful.

**Comment by timabell** [comment] 2015-08-16 22:05
@mgrojo exporting the back-end is definitely beyond the scope of this project but is certainly sensible. Something like http://ready-roll.com/ works well for sql server databases. (I purchased it for my contract work and can personally recommend it.)

**Comment by timabell** [comment] 2015-08-19 16:45
Could those who are interested in this bug take a look at PR #22 and comment on whether you think it should be merged in. Thanks
@p0lar-bear @jwbrookes @stessler @CrispinF

**Comment by Ronaldvr** [comment] 2015-08-20 09:29
Hi, To make matters a bit more complicated, I am currently using the below routine that writes (and reads) an XML file for relations. The benefits are that there are no reasons to convert odd characters, the downside is that I have chosen to recreate relation names if they are > 64 characters. Code below.

```vba
Option Compare Database

Option Explicit

Public Sub ExportRelation(rel As DAO.Relation, outfile As Variant)
    Dim f As DAO.Field
    Dim strNm As String
    
    outfile.WriteLine "<Relation>"
    If InStr(rel.name, ":\") > 0 Then
        'names with linked table names get unwieldy long and left(64) thus not very descriptive, and may even cause a same name clash
        strNm = Replace(rel.Table & "_" & rel.Fields(0).name, " ", "_") & "_to_" & Replace(rel.ForeignTable & "_" & rel.Fields(0).ForeignName, " ", "_")
    Else
        strNm = rel.name
    End If

    outfile.WriteLine "<RelationName>" & Right(strNm, 64) & "</RelationName>"
    outfile.WriteLine "<RelationAttributes>" & rel.Attributes & "</RelationAttributes>" 'RelationAttributeEnum
    outfile.WriteLine "<RelationTable>" & rel.Table & "</RelationTable>"
    outfile.WriteLine "<RelationforeignTable>" & rel.ForeignTable & "</RelationforeignTable>"
    outfile.WriteLine "<Fields>"
    For Each f In rel.Fields
        outfile.WriteLine "<FieldName>" & f.name & "</FieldName>"
        outfile.WriteLine "<FieldForeignName>" & f.ForeignName & "</FieldForeignName>"
    Next
    outfile.WriteLine "</Fields>"
    outfile.WriteLine "</Relation>"

End Sub
Public Function ImportRelation(filePath As String) As Long

Dim xmlDoc As Object
Set xmlDoc = CreateObject("MSXML2.DOMDocument")
Dim xmlNode As Object 'MSXML2.IXMLDOMNode
Dim xmlFldNode As Object 'MSXML2.IXMLDOMNode
Dim xmlElements As Object 'MSXML2.IXMLDOMNode
Dim xmlElements1 As Object 'MSXML2.IXMLDOMNode
Dim xmlElements2 As Object 'MSXML2.IXMLDOMNode
Dim I As Integer
Dim n As Long
Dim strNm As String
Dim rel As DAO.Relation
Dim FLd As DAO.Field

xmlDoc.async = False
xmlDoc.Load filePath
n = 0
For Each xmlNode In xmlDoc.FirstChild.ChildNodes
    Set rel = New DAO.Relation
    Set xmlElements = xmlNode.getElementsByTagName("RelationTable")
    rel.Table = xmlElements.item(0).Text
    Set xmlElements = xmlNode.getElementsByTagName("RelationforeignTable")
    rel.ForeignTable = xmlElements.item(0).Text
    Set xmlElements = xmlNode.getElementsByTagName("RelationAttributes")
    rel.Attributes = CLng(xmlElements.item(0).Text)
    Set xmlFldNode = xmlNode.SelectSingleNode("Fields")
    Set xmlElements1 = xmlNode.getElementsByTagName("FieldName")
    Set xmlElements2 = xmlNode.getElementsByTagName("FieldForeignName")
    For I = 0 To xmlElements1.Length - 1
        Set FLd = New DAO.Field
        FLd.name = xmlElements1.item(I).Text
        FLd.ForeignName = xmlElements2.item(I).Text
        rel.Fields.Append FLd
    Next
    strNm = Replace(rel.Table & "_" & rel.Fields(0).name, " ", "_") & "_to_" & Replace(rel.ForeignTable & "_" & rel.Fields(0).ForeignName, " ", "_")
    Set xmlElements = xmlNode.getElementsByTagName("RelationName")
    If InStr(xmlElements.item(0).Text, ":\") > 0 Then
        'names with linked table names get unwieldy long and left(64) thus not very descriptive, and may even cause a same name clash
        rel.name = Left(strNm, 64)
    Else
        rel.name = Right(xmlElements.item(0).Text, 64)
    End If
    CurrentDb.Relations.Append rel
    n = n + 1
Next

ImportRelation = n

End Function


```

**Comment by Ronaldvr** [comment] 2015-08-20 09:32
And in VCS_Import_Export the code that calls the routine is as follows:

```vba
    Dim aRelation As DAO.Relation
    Dim FSO, outfile As Object
    Set FSO = CreateObject("Scripting.FileSystemObject")
    Set outfile = FSO.CreateTextFile(obj_path & "Relations.XML", True)
    outfile.WriteLine "<Relations>"

    For Each aRelation In CurrentDb.Relations
    
        If Not (aRelation.name = "MSysNavPaneGroupsMSysNavPaneGroupToObjects" Or aRelation.name = "MSysNavPaneGroupCategoriesMSysNavPaneGroups") Then
            If CurrentProject.FileFormat >= 12# Then
                VCS_Relation.ExportRelation aRelation, outfile
            Else 'MDB database
                VCS_Relation.ExportRelation aRelation, outfile
            End If
            obj_count = obj_count + 1
        End If
    Next
    outfile.WriteLine "</Relations>"
    outfile.Close


```

**Comment by timabell** [comment] 2015-08-20 09:34
@Ronaldvr it would be tidier & easier to deal with to include a link to your fork/branch on github that has that code rather than pasting it all here. Thanks for sharing though.

**Comment by Ronaldvr** [comment] 2015-08-20 10:47
Hi Tim,

I know, sorry about that: been on holiday, and have as yet been unable to get my repository in order... So I decided to pust it as is. I will keep trying with my repo though, so as soon as I am able to get it in sync again I will commit it.

**Comment by timabell** [comment] 2015-08-20 11:01
cool, no worries

**Comment by mgrojo** [comment] 2015-08-20 14:20
Why should be these linked relations exported? It is not orthogonal with not exporting the linked table definitions. For both of them I'm exporting the back-end (in my case another accdb file with only tables and their relations) independently of the front-end. Is the case different when the back-end is SQL Server or another database through ODBC? 

Currently the code is breaking when there are linked relations, so I recommend to accept my change although in the future a better approach for this kind of relations could be found.

**Comment by timabell** [comment] 2015-08-20 14:22
I'm with @mgrojo on this I think. Makes sense to unbreak it for now, and then open a new enhancement issue on github for adding export of these fks.

**Comment by Ronaldvr** [comment] 2015-08-20 16:29
I do not know whether you can add relations in the front end that do not exist on the backend? Perhaps it would be wise to test that as well...

**Comment by mgrojo** [comment] 2015-08-20 18:36
Yes, it is possible to add new relations in the front-end. On the other hand, it isn't possible to modify relations coming from the back-end from the front-end.

What I do is to maintain the relations only in the back-end, except for cases that I need a relation for a query that is only in the front-end. At least with this scenario the current code of my fork is working well exporting and importing both files, back-end and front-end. The relations are imported in each case where they belong, and when the linked tables are imported in the front-end, the linked relations are automatically visible.

**Comment by timabell** [comment] 2015-08-20 18:51
merged

**Closed by timabell** 2015-08-20 18:51 UTC
Labels: bug, help wanted
